import './Head.css'
export const Head = () => {
    return (
      <div className='Container'>
        <h1 className='Title'>Reframe Image Generator</h1>
        <span className='Description'>
          The Reframe search engine.
        </span>
        <span className='content'>
          Images generated by AI.
        </span>
      </div>
    )
  }
  